import { Poppins, Inter } from "next/font/google";
import "./globals.css";



const poppins = Poppins({
  variable:"--font-poppins",
  weight:["400","500","600","700"],
  subsets:["latin"],
})

const inter = Inter({
  variable:"--font-inter",
  weight:["400","500","600","700"],
  subsets:["latin"],
})


export const metadata = {
  title: "Fresh Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
